// <auto-generated />
using System;
using AdvAsmPlanning.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvAsmPlanning.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203193001_RenameForecastToMainGridAndPlanningScenarioToScenario")]
    partial class RenameForecastToMainGridAndPlanningScenarioToScenario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvAsmPlanning.Domain.Database.Department", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("c_BoardorGAAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Component")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("c_DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("c_Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Entity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_FinanceOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_HRBusinessPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_IncludedInBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_IncludedInGAAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_InitialOrganicPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_IsLeaf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_MPCCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OMSRevenueAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OperatingSegment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OperatingUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OrganizationGroup1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OrganizationGroup2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OrganizationGroup3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Partition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Passthrough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_PeriodAcquired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_PshReportRollup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_SalesLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_Segment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.Account", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<string>("AccountCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitCredit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("c_AccountFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_AccountSubgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_AcctWaterfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_AllocationRollup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_DemoSubgroup1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_DemoSubgroup2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_DemoSubgroup3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_EBITDARollup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_ExtReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_FLUXRollup1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_FLUXRollup2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_ForeignCurrencyRevaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_GAAP_NONGAAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_IsSuspended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_MockEPML1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_MockEPML2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_MockEPML3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_MockEPML4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_NavisionGLCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OMSRevenueAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_OMSRevenueAccountDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_RollupLevel0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_RollupLevel1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_RollupLevel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_SAP_GL_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_SalesRollupLevel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("c_SignMultiplier")
                        .HasColumnType("bigint");

                    b.HasKey("MemberId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            ConcurrencyStamp = "6A1E2C53-874C-4710-9828-5C761B5919BD",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1002L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B0A3D1CF-679E-4C9E-92A7-2FDFB5C01F44",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFj9Zqgbi0FbS0mMGtPpXyQt1K2dI4XFa7Q0Jm4ByfgfH5AjFq5RZkGW9xO+fAO3KA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "C88FA612-1790-4B5B-9AA0-560F50FC7B72",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.MainGrid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Delta")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoFind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MainGrids");
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.MainGridActual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MainGridId")
                        .HasColumnType("bigint");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainGridId");

                    b.ToTable("MainGridActuals");
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.Scenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActualScenario")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsolidationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CubeScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FxFlag")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanningScenarioGroupId")
                        .HasColumnType("int");

                    b.Property<int>("PostingLayerId")
                        .HasColumnType("int");

                    b.Property<string>("StartMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1002L,
                            RoleId = 1001L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.MainGridActual", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.MainGrid", "MainGrid")
                        .WithMany("Actuals")
                        .HasForeignKey("MainGridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainGrid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("AdvAsmPlanning.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvAsmPlanning.Domain.Entities.MainGrid", b =>
                {
                    b.Navigation("Actuals");
                });
#pragma warning restore 612, 618
        }
    }
}
