// <auto-generated />
using System;
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126224354_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Dropdowns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(280),
                            Key = "BusinessUnit",
                            Label = "Business Unit 1",
                            Value = "BU1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(818),
                            Key = "BusinessUnit",
                            Label = "Business Unit 2",
                            Value = "BU2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(820),
                            Key = "BusinessUnit",
                            Label = "Business Unit 3",
                            Value = "BU3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(821),
                            Key = "BusinessUnit",
                            Label = "Business Unit 4",
                            Value = "BU4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(822),
                            Key = "BusinessUnit",
                            Label = "Business Unit 5",
                            Value = "BU5"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(822),
                            Key = "Division",
                            Label = "Division 1",
                            Value = "Div1"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(823),
                            Key = "Division",
                            Label = "Division 2",
                            Value = "Div2"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(824),
                            Key = "Division",
                            Label = "Division 3",
                            Value = "Div3"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(825),
                            Key = "Division",
                            Label = "Division 4",
                            Value = "Div4"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(825),
                            Key = "Division",
                            Label = "Division 5",
                            Value = "Div5"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(826),
                            Key = "Market",
                            Label = "Market 1",
                            Value = "Mkt1"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(827),
                            Key = "Market",
                            Label = "Market 2",
                            Value = "Mkt2"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(827),
                            Key = "Market",
                            Label = "Market 3",
                            Value = "Mkt3"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(835),
                            Key = "Market",
                            Label = "Market 4",
                            Value = "Mkt4"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(836),
                            Key = "Market",
                            Label = "Market 5",
                            Value = "Mkt5"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(837),
                            Key = "DepartmentName",
                            Label = "Department Name 1",
                            Value = "DeptName1"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(837),
                            Key = "DepartmentName",
                            Label = "Department Name 2",
                            Value = "DeptName2"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(838),
                            Key = "DepartmentName",
                            Label = "Department Name 3",
                            Value = "DeptName3"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(839),
                            Key = "DepartmentName",
                            Label = "Department Name 4",
                            Value = "DeptName4"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(839),
                            Key = "DepartmentName",
                            Label = "Department Name 5",
                            Value = "DeptName5"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(840),
                            Key = "DepartmentRange",
                            Label = "Department Range 1",
                            Value = "DeptRange1"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(841),
                            Key = "DepartmentRange",
                            Label = "Department Range 2",
                            Value = "DeptRange2"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(846),
                            Key = "DepartmentRange",
                            Label = "Department Range 3",
                            Value = "DeptRange3"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(847),
                            Key = "DepartmentRange",
                            Label = "Department Range 4",
                            Value = "DeptRange4"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(848),
                            Key = "DepartmentRange",
                            Label = "Department Range 5",
                            Value = "DeptRange5"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(848),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 1",
                            Value = "AccExt1"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(849),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 2",
                            Value = "AccExt2"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(850),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 3",
                            Value = "AccExt3"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(851),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 4",
                            Value = "AccExt4"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(851),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 5",
                            Value = "AccExt5"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(852),
                            Key = "AccountGroup",
                            Label = "Account Group 1",
                            Value = "AccGroup1"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(853),
                            Key = "AccountGroup",
                            Label = "Account Group 2",
                            Value = "AccGroup2"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(859),
                            Key = "AccountGroup",
                            Label = "Account Group 3",
                            Value = "AccGroup3"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(860),
                            Key = "AccountGroup",
                            Label = "Account Group 4",
                            Value = "AccGroup4"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(860),
                            Key = "AccountGroup",
                            Label = "Account Group 5",
                            Value = "AccGroup5"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(861),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 1",
                            Value = "AccSub1"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(862),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 2",
                            Value = "AccSub2"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(862),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 3",
                            Value = "AccSub3"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(863),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 4",
                            Value = "AccSub4"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(864),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 5",
                            Value = "AccSub5"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(864),
                            Key = "AccountName",
                            Label = "Account Name 1",
                            Value = "AccName1"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(865),
                            Key = "AccountName",
                            Label = "Account Name 2",
                            Value = "AccName2"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 367, DateTimeKind.Utc).AddTicks(867),
                            Key = "AccountName",
                            Label = "Account Name 3",
                            Value = "AccName3"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2485),
                            Key = "AccountName",
                            Label = "Account Name 4",
                            Value = "AccName4"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2492),
                            Key = "AccountName",
                            Label = "Account Name 5",
                            Value = "AccName5"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2494),
                            Key = "AccountRange",
                            Label = "Account Range 1",
                            Value = "AccRange1"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2500),
                            Key = "AccountRange",
                            Label = "Account Range 2",
                            Value = "AccRange2"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2501),
                            Key = "AccountRange",
                            Label = "Account Range 3",
                            Value = "AccRange3"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2502),
                            Key = "AccountRange",
                            Label = "Account Range 4",
                            Value = "AccRange4"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 369, DateTimeKind.Utc).AddTicks(2503),
                            Key = "AccountRange",
                            Label = "Account Range 5",
                            Value = "AccRange5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 100.50m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(6793),
                            Date = new DateTime(2025, 11, 25, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(6944)
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 200.75m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7292),
                            Date = new DateTime(2025, 11, 24, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7293)
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 50.00m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7295),
                            Date = new DateTime(2025, 11, 23, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7296)
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 300.20m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7297),
                            Date = new DateTime(2025, 11, 22, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7297)
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 150.00m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7298),
                            Date = new DateTime(2025, 11, 21, 22, 43, 52, 366, DateTimeKind.Utc).AddTicks(7298)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.HasOne("Domain.Entities.Dropdown", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
