// <auto-generated />
using System;
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127191036_FixDataSeedTimestamps")]
    partial class FixDataSeedTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Dropdowns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BusinessUnit",
                            Label = "Business Unit 1",
                            Value = "BU1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BusinessUnit",
                            Label = "Business Unit 2",
                            Value = "BU2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BusinessUnit",
                            Label = "Business Unit 3",
                            Value = "BU3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BusinessUnit",
                            Label = "Business Unit 4",
                            Value = "BU4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BusinessUnit",
                            Label = "Business Unit 5",
                            Value = "BU5"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Division",
                            Label = "Division 1",
                            Value = "Div1"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Division",
                            Label = "Division 2",
                            Value = "Div2"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Division",
                            Label = "Division 3",
                            Value = "Div3"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Division",
                            Label = "Division 4",
                            Value = "Div4"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Division",
                            Label = "Division 5",
                            Value = "Div5"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Market",
                            Label = "Market 1",
                            Value = "Mkt1"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Market",
                            Label = "Market 2",
                            Value = "Mkt2"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Market",
                            Label = "Market 3",
                            Value = "Mkt3"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Market",
                            Label = "Market 4",
                            Value = "Mkt4"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "Market",
                            Label = "Market 5",
                            Value = "Mkt5"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentName",
                            Label = "Department Name 1",
                            Value = "DeptName1"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentName",
                            Label = "Department Name 2",
                            Value = "DeptName2"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentName",
                            Label = "Department Name 3",
                            Value = "DeptName3"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentName",
                            Label = "Department Name 4",
                            Value = "DeptName4"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentName",
                            Label = "Department Name 5",
                            Value = "DeptName5"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentRange",
                            Label = "Department Range 1",
                            Value = "DeptRange1"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentRange",
                            Label = "Department Range 2",
                            Value = "DeptRange2"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentRange",
                            Label = "Department Range 3",
                            Value = "DeptRange3"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentRange",
                            Label = "Department Range 4",
                            Value = "DeptRange4"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "DepartmentRange",
                            Label = "Department Range 5",
                            Value = "DeptRange5"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 1",
                            Value = "AccExt1"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 2",
                            Value = "AccExt2"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 3",
                            Value = "AccExt3"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 4",
                            Value = "AccExt4"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountExternalReport",
                            Label = "Account External Report 5",
                            Value = "AccExt5"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountGroup",
                            Label = "Account Group 1",
                            Value = "AccGroup1"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountGroup",
                            Label = "Account Group 2",
                            Value = "AccGroup2"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountGroup",
                            Label = "Account Group 3",
                            Value = "AccGroup3"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountGroup",
                            Label = "Account Group 4",
                            Value = "AccGroup4"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountGroup",
                            Label = "Account Group 5",
                            Value = "AccGroup5"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 1",
                            Value = "AccSub1"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 2",
                            Value = "AccSub2"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 3",
                            Value = "AccSub3"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 4",
                            Value = "AccSub4"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountSubGroup",
                            Label = "Account SubGroup 5",
                            Value = "AccSub5"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountName",
                            Label = "Account Name 1",
                            Value = "AccName1"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountName",
                            Label = "Account Name 2",
                            Value = "AccName2"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountName",
                            Label = "Account Name 3",
                            Value = "AccName3"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountName",
                            Label = "Account Name 4",
                            Value = "AccName4"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountName",
                            Label = "Account Name 5",
                            Value = "AccName5"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountRange",
                            Label = "Account Range 1",
                            Value = "AccRange1"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountRange",
                            Label = "Account Range 2",
                            Value = "AccRange2"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountRange",
                            Label = "Account Range 3",
                            Value = "AccRange3"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountRange",
                            Label = "Account Range 4",
                            Value = "AccRange4"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "AccountRange",
                            Label = "Account Range 5",
                            Value = "AccRange5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Forecast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoFind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("Domain.Entities.ForecastActual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ForecastId")
                        .HasColumnType("bigint");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForecastId");

                    b.ToTable("ForecastActuals");
                });

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.HasOne("Domain.Entities.Dropdown", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.ForecastActual", b =>
                {
                    b.HasOne("Domain.Entities.Forecast", null)
                        .WithMany("Actuals")
                        .HasForeignKey("ForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Dropdown", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Entities.Forecast", b =>
                {
                    b.Navigation("Actuals");
                });
#pragma warning restore 612, 618
        }
    }
}
