// <auto-generated />
using System;
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 100.50m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9162),
                            Date = new DateTime(2025, 11, 25, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9290)
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 200.75m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9591),
                            Date = new DateTime(2025, 11, 24, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9592)
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 50.00m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9594),
                            Date = new DateTime(2025, 11, 23, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9594)
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 300.20m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9595),
                            Date = new DateTime(2025, 11, 22, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9596)
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 150.00m,
                            CreatedAt = new DateTime(2025, 11, 26, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9596),
                            Date = new DateTime(2025, 11, 21, 22, 8, 40, 877, DateTimeKind.Utc).AddTicks(9597)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
