using AdvAsmPlanning.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace AdvAsmPlanning.Domain.Database;

public static class PlanningScenarioDataSeeder
{
    public static async Task SeedPlanningScenarios(ApplicationDbContext context)
    {
        // Check if planning scenarios already exist
        if (await context.PlanningScenarios.AnyAsync())
        {
            return; // Data already seeded
        }

        var scenarios = new List<PlanningScenario>
        {
            new() { Code = "BUD", Description = "Budget 2024", CreatedAt = new DateTime(2018, 6, 18, 10, 58, 58, 187, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 6, 18, 10, 58, 58, 187, DateTimeKind.Utc), CubeScenarioId = -6, StartMessage = "The 2024 Budget scenario is now open.", ConsolidationNumber = "801", ActualScenario = true, FxFlag = true, PlanningScenarioGroupId = 3, PostingLayerId = 1 },
            new() { Code = "FOR", Description = "Forecast", CreatedAt = new DateTime(2018, 6, 18, 10, 59, 18, 877, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 6, 18, 10, 59, 18, 877, DateTimeKind.Utc), CubeScenarioId = -5, ConsolidationNumber = "800", ActualScenario = true, FxFlag = true, PlanningScenarioGroupId = 6, PostingLayerId = 1 },
            new() { Code = "FCST", Description = "Current Forecast", CreatedAt = new DateTime(2018, 7, 30, 17, 15, 24, 547, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 7, 30, 17, 15, 24, 547, DateTimeKind.Utc), ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 28, PostingLayerId = 1 },
            new() { Code = "CTL03", Description = "CTL 2019", CreatedAt = new DateTime(2018, 7, 16, 13, 40, 15, 170, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 7, 16, 13, 40, 15, 170, DateTimeKind.Utc), CubeScenarioId = -7, ConsolidationNumber = "802", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 32, PostingLayerId = 1 },
            new() { Code = "FCSTP", Description = "Prior Forecast", CreatedAt = new DateTime(2018, 7, 30, 17, 15, 48, 280, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 7, 30, 17, 15, 48, 280, DateTimeKind.Utc), ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 34, PostingLayerId = 1 },
            new() { Code = "BUD2018", Description = "2018 Budget", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2018, 8, 7, 13, 39, 51, 383, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2018, 8, 7, 13, 39, 51, 383, DateTimeKind.Utc), CubeScenarioId = -8, StartMessage = "", ConsolidationNumber = "803", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 37, PostingLayerId = 1 },
            new() { Code = "EXTPROJ", Description = "Extended Project", CreatedAt = new DateTime(2018, 12, 27, 16, 46, 9, 297, DateTimeKind.Utc), UpdatedAt = new DateTime(2018, 12, 27, 16, 46, 9, 297, DateTimeKind.Utc), CubeScenarioId = -9, ConsolidationNumber = "804", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 67, PostingLayerId = 1 },
            new() { Code = "DigTechStrech", Description = "Digital Technology 2019 Stretch Budget", CreatedAt = new DateTime(2019, 1, 31, 11, 58, 21, 593, DateTimeKind.Utc), UpdatedAt = new DateTime(2019, 1, 31, 11, 58, 21, 593, DateTimeKind.Utc), CubeScenarioId = -11, StartMessage = "Welcome Loren and team to the stretch goal section of the Digital Technology Budget!", ConsolidationNumber = "805", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 71, PostingLayerId = 1 },
            new() { Code = "PREDICTIVEANALYTICS", Description = "Predictive Analytics", CreatedAt = new DateTime(2019, 1, 31, 11, 56, 29, 383, DateTimeKind.Utc), UpdatedAt = new DateTime(2019, 1, 31, 11, 56, 29, 383, DateTimeKind.Utc), CubeScenarioId = -10, StartMessage = "Load Predictive Analytics Data", ConsolidationNumber = "806", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 72, PostingLayerId = 1 },
            new() { Code = "ACTPLUSBUD", Description = "Budget 2019 & Actuals", CreatedAt = new DateTime(2019, 3, 6, 13, 18, 33, 357, DateTimeKind.Utc), UpdatedAt = new DateTime(2019, 3, 6, 13, 18, 33, 357, DateTimeKind.Utc), ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 77, PostingLayerId = 1 },
            new() { Code = "ACQUISITIONTARGET", Description = "Acquisition Target", CreatedAt = new DateTime(2019, 6, 4, 11, 20, 52, 583, DateTimeKind.Utc), UpdatedAt = new DateTime(2019, 6, 4, 11, 20, 52, 583, DateTimeKind.Utc), CubeScenarioId = -12, ConsolidationNumber = "807", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 83, PostingLayerId = 1 },
            new() { Code = "BUD2019", Description = "2019 Budget", CreatedAt = new DateTime(2019, 8, 30, 9, 46, 25, 460, DateTimeKind.Utc), UpdatedAt = new DateTime(2019, 8, 30, 9, 46, 25, 460, DateTimeKind.Utc), CubeScenarioId = -13, ConsolidationNumber = "808", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 89, PostingLayerId = 1 },
            new() { Code = "CTL04", Description = "CTL 2020", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2019, 9, 9, 14, 45, 56, 637, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2019, 9, 9, 14, 45, 56, 637, DateTimeKind.Utc), CubeScenarioId = -14, ConsolidationNumber = "810", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 90, PostingLayerId = 1 },
            new() { Code = "ACTSTAT", Description = "Actual Statistical", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2020, 1, 21, 9, 9, 16, 810, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2020, 1, 21, 9, 9, 16, 810, DateTimeKind.Utc), CubeScenarioId = -15, StartMessage = "", ConsolidationNumber = "811", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 97, PostingLayerId = 1 },
            new() { Code = "FORPRE", Description = "Pre-Forecast", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2020, 3, 4, 14, 38, 15, 200, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2020, 3, 4, 14, 38, 15, 200, DateTimeKind.Utc), CubeScenarioId = -16, StartMessage = "", ConsolidationNumber = "812", ActualScenario = true, FxFlag = true, PlanningScenarioGroupId = 100, PostingLayerId = 1 },
            new() { Code = "COVID", Description = "COVID", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2020, 9, 3, 16, 40, 49, 970, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2020, 9, 3, 16, 40, 49, 970, DateTimeKind.Utc), CubeScenarioId = -17, StartMessage = "", ConsolidationNumber = "813", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 126, PostingLayerId = 1 },
            new() { Code = "BUD2020", Description = "2020 Budget", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2020, 9, 14, 11, 15, 37, 330, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2020, 9, 14, 11, 15, 37, 330, DateTimeKind.Utc), CubeScenarioId = -18, ConsolidationNumber = "814", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 127, PostingLayerId = 1 },
            new() { Code = "CTL2021", Description = "CTL 2021", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2020, 9, 18, 13, 15, 47, 197, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2020, 9, 18, 13, 15, 47, 197, DateTimeKind.Utc), CubeScenarioId = -19, StartMessage = "", ConsolidationNumber = "815", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 128, PostingLayerId = 1 },
            new() { Code = "BUDHEDGE", Description = "Budget Hedge", CreatedBy = "ASM\\ccernosek.admin", CreatedAt = new DateTime(2021, 2, 2, 12, 15, 27, 133, DateTimeKind.Utc), LastUpdatedBy = "ASM\\ccernosek.admin", UpdatedAt = new DateTime(2021, 2, 2, 12, 15, 27, 133, DateTimeKind.Utc), CubeScenarioId = -20, StartMessage = "", ConsolidationNumber = "816", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 3, PostingLayerId = 4 },
            new() { Code = "Target", Description = "Target", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2021, 3, 19, 8, 28, 8, 23, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2021, 3, 19, 8, 28, 8, 23, DateTimeKind.Utc), CubeScenarioId = -21, StartMessage = "", ConsolidationNumber = "817", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 147, PostingLayerId = 1 },
            new() { Code = "BUD2021", Description = "2021 Budget", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2021, 9, 16, 8, 37, 54, 650, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2021, 9, 16, 8, 37, 54, 650, DateTimeKind.Utc), CubeScenarioId = -22, ConsolidationNumber = "818", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 156, PostingLayerId = 1 },
            new() { Code = "BUDHEDGE2021", Description = "Budget Hedge 2021", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2021, 9, 16, 8, 40, 41, 870, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2021, 9, 16, 8, 40, 41, 870, DateTimeKind.Utc), CubeScenarioId = -23, ConsolidationNumber = "819", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 156, PostingLayerId = 4 },
            new() { Code = "BUD2022", Description = "BUD2022", CreatedBy = "ASM\\garrett.sisley", CreatedAt = new DateTime(2021, 10, 5, 16, 54, 36, 193, DateTimeKind.Utc), LastUpdatedBy = "ASM\\garrett.sisley", UpdatedAt = new DateTime(2021, 10, 5, 16, 54, 36, 193, DateTimeKind.Utc), CubeScenarioId = -27, StartMessage = "", ConsolidationNumber = "826", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 163, PostingLayerId = 1 },
            new() { Code = "CTL2023", Description = "CTL 2023", CreatedBy = "ASM\\yasir.fazal", CreatedAt = new DateTime(2022, 9, 22, 3, 42, 6, 27, DateTimeKind.Utc), LastUpdatedBy = "ASM\\yasir.fazal", UpdatedAt = new DateTime(2022, 9, 22, 3, 42, 6, 27, DateTimeKind.Utc), CubeScenarioId = -26, StartMessage = "", ConsolidationNumber = "822", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 192, PostingLayerId = 1 },
            new() { Code = "BUDHEDGE2022", Description = "Budget2022", CreatedBy = "ASM\\yasir.fazal", CreatedAt = new DateTime(2022, 10, 28, 11, 15, 12, 570, DateTimeKind.Utc), LastUpdatedBy = "ASM\\yasir.fazal", UpdatedAt = new DateTime(2022, 10, 28, 11, 15, 12, 570, DateTimeKind.Utc), CubeScenarioId = -28, StartMessage = "", ConsolidationNumber = "827", ActualScenario = true, FxFlag = false, PlanningScenarioGroupId = 3, PostingLayerId = 4 },
            new() { Code = "LRP", Description = "Long Range Plan", CreatedBy = "ASM\\sakerele.admin", CreatedAt = new DateTime(2023, 9, 12, 6, 19, 47, 203, DateTimeKind.Utc), LastUpdatedBy = "ASM\\sakerele.admin", UpdatedAt = new DateTime(2023, 9, 12, 6, 19, 47, 203, DateTimeKind.Utc), CubeScenarioId = -29, StartMessage = "", ConsolidationNumber = "828", ActualScenario = true, FxFlag = true, PlanningScenarioGroupId = 217, PostingLayerId = 1 },
            new() { Code = "LRPHEDGE", Description = "Long Range Plan Hedge", CreatedBy = "ASM\\sakerele.admin", CreatedAt = new DateTime(2023, 9, 12, 6, 20, 40, 210, DateTimeKind.Utc), LastUpdatedBy = "ASM\\sakerele.admin", UpdatedAt = new DateTime(2023, 9, 12, 6, 20, 40, 210, DateTimeKind.Utc), CubeScenarioId = -30, StartMessage = "", ConsolidationNumber = "829", ActualScenario = true, FxFlag = true, PlanningScenarioGroupId = 217, PostingLayerId = 4 }
        };

        await context.PlanningScenarios.AddRangeAsync(scenarios);
        await context.SaveChangesAsync();
    }
}
